import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Nav } from "./navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function Layout({ children }: LayoutProps) {
  return (
    <html>
      <body className="w-9/10 m-auto font-sans bg-zinc-50 dark:bg-black dark:text-white">
        <div className="min-h-screen flex flex-col">
          <Nav />
          <main className="flex-1 container py-8">{children}</main>

          <footer className="border-t py-4 text-center text-sm text-muted-foreground">
            © 2025 Delta super-special elite coding Inc. All rights reserved.
          </footer>
        </div>
      </body>
    </html>
  );
}
