import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Nav } from "./navigation";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="font-sans bg-zinc-50 dark:bg-black dark:text-white">
        <Nav />
        <div className="sm:w-9/10 m-auto min-h-screen flex flex-col">
          <main className="flex-1 container py-8">{children}</main>

          <footer className="border-t py-4 text-center text-sm text-muted-foreground">
            © 2025 Delta super-special elite coding Inc. All rights reserved.
          </footer>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
